### PR TITLE
fix: safeStringify may return undefined

### PR DESCRIPTION
**Pull request by P0lip**
This indirectly caused https://stoplight-internal.slack.com/archives/C01019NT0P8/p1596722416373400?thread_ts=1596722262.372400&cid=C01019NT0P8

### CODE REVIEW

**Comment by marbemac** [comment]
This might end up breaking types in a bunch of downstream packages - will have to check and update!

**Comment by P0lip** [comment]
>This might end up breaking types in a bunch of downstream packages - will have to check and update!

Yeah, I'm aware of it. Might be painful, but at least the risk of TypeErrors will be lower.

**Comment by P0lip** [comment]
@marcelltoth did you want to use an overload? :grin:

**Comment by marcelltoth** [comment]
Yes. But then we should make sure it does not. And write tests for it. It's not a good excuse to break all scenarios even where we do know that the input is an object / boolean / string.

This does compile and is much less of a breaking change:
```typescript
type Replacer = (key: string, value: any) => any | Array<number | string> | null;


export function safeStringify(
  value: undefined,
  replacer?: Replacer,
  space?: string | number,
): undefined
export function safeStringify<T extends {}>(
  value: T,
  replacer?: Replacer,
  space?: string | number,
): string
export function safeStringify<T>(
  value: T,
  replacer?: Replacer,
  space?: string | number,
): Optional<string> {
  if (typeof value === 'string') {
    return value;
  }

  try {
    // try regular stringify first as mentioned in this tip:
    // https://github.com/davidmarkclements/fast-safe-stringify#protip
    return JSON.stringify(value, replacer, space);
  } catch {
    return fastStringify(value, replacer, space);
  }
};

```

**Comment by P0lip** [comment]
@marcelltoth, this won't work.
Consider the following scenario:
```ts
  expect(safeStringify( {
      toJSON() {
        return void 0;
      }
    })).toBeUndefined();
```

**Pull request merged**
