### PR TITLE
chore(deps): bump json5 to 2.2.2 version

### PR DESCRIPTION
**Pull request by SB-venkatyadavilli**
## Motivation and Context

[STOP-944](https://smartbear.atlassian.net/browse/STOP-944)

## Description

to resolve the vulnerability, have bumped json5 version to 2.2.2v.

## How Has This Been Tested?

Tested locally by executing the build, test, test.prod, test.update, lint, lint.fix commands. All commands executed successfully. Also done testing with prism repo using yalc.

## Screenshot(s)/recordings(s)

image
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] This PR's code follows as closely as possible [the coding style/guidelines of this project](???).
- [ ] I have added error reporting and followed [the error reporting guidelines](???).
- [ ] I have added event tracking and followed [the event tracking guidelines](???).
- [ ] I have updated any relevant documentation accordingly to reflect this PR's changes.
- [ ] I have added automated tests (unit/integration/e2e/other) to cover my changes.
- [ ] All new and existing tests pass locally (excluding flaky CI tests).

[STOP-944]: https://smartbear.atlassian.net/browse/STOP-944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by SB-rohitdesai — COMMENTED** [review]
Please do yalc testing in prism and platform-internal

**Comment by SB-venkatyadavilli** [comment]
> Please do yalc testing in prism and platform-internal

have tested yalc testing in prism

**Comment by SB-pradeep-bande** [comment]
looks good to me.

**Review by SB-rohitdesai — APPROVED** [review]
LGTM

**Pull request merged**
