### PR TITLE
feat: make getLocationForJsonPath more consistent with the YAML equivalent [SO-215]

### PR DESCRIPTION
**Pull request by P0lip**
There was a minor inconsistency between JSON variant of `getLocationForJsonPath` and the YAML one.
In the case of YAML, the lookup is more relaxed and does not bail out entirely if a node at a given path does not exist.
It always returns the closest node while the JSON equivalent returns undefined.
This lead to a few subtle issues with Spectral relaxed returns the closest parent for a given path.
This PR unifies it and makes results more predictable.

### CODE REVIEW

**Comment by wmhilton** [comment]
I can't tell from your description whether the new standard behavior is more relaxed or more strict. Is it more strict?

**Comment by P0lip** [comment]
The new one is less strict. Currently, we don't return any location if given json path does not exist, while the YAML variant does return some (scoped to closest found parent).

**Comment by wmhilton** [comment]
Do we want more relaxed because of the live-editing of files? I'm trying to understand why we should be forgiving. If a node doesn't exist shouldn't we treat it as if it doesn't exist?

**Comment by P0lip** [comment]
@wmhilton 
It's primarily because of Spectral. There are rules performing lookups on nonexistent paths - in such case, location is not found and we default to a 'naive' location (line -> 0, char -> 0). This is rather not informative feedback.
Obviously, we could have a different check in Spectral yet this would come at cost, as we'd need to execute `getLocationForJsonPath` a couple of times.

>  If a node doesn't exist shouldn't we treat it as if it doesn't exist?

Well, I was thinking about that - in fact, this might be desired under certain conditions.
I'd suggest hiding it behind a flag.
```
function getLocationForJsonPath(result: IParserResult, path: JsonPath, closest?: boolean): ILocation | void;
```
thoughts?

**Comment by wmhilton** [comment]
> thoughts?

I like the `closest?: boolean` idea. That way you have to explicitly opt in to "helpful" behavior. :-)

Another idea I had though was if the node is missing, have the function go ahead and create the missing node with some default values. :trollface:

**Comment by P0lip** [comment]
> Another idea I had though was if the node is missing, have the function go ahead and create the missing node with some default values. :trollface:

:rofl:

**Comment by P0lip** [comment]
Needs https://github.com/stoplightio/types/pull/32

**Pull request merged**
